/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const EffectScope: typeof import('vue').EffectScope
  const cn: typeof import('./lib/utils').cn
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createCache: typeof import('./lib/cache').createCache
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const effectScope: typeof import('vue').effectScope
  const formatDateSafe: typeof import('./lib/utils').formatDateSafe
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getOgImageUrl: typeof import('./lib/utils').getOgImageUrl
  const getPageTitleKey: typeof import('./lib/utils').getPageTitleKey
  const h: typeof import('vue').h
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const loadCurrency: typeof import('./composables/useCurrency').loadCurrency
  const loading: typeof import('./composables/useAuth').loading
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAccounts: typeof import('./composables/useAccounts').useAccounts
  const useActivityLog: typeof import('./composables/useActivityLog').useActivityLog
  const useAttrs: typeof import('vue').useAttrs
  const useAuth: typeof import('./composables/useAuth').useAuth
  const useBills: typeof import('./composables/useBills').useBills
  const useBudgets: typeof import('./composables/useBudgets').useBudgets
  const useCamera: typeof import('./composables/useCamera').useCamera
  const useCategories: typeof import('./composables/useCategories').useCategories
  const useCategoryStats: typeof import('./composables/useTransactions').useCategoryStats
  const useColorMode: typeof import('./composables/nuxt-compat').useColorMode
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useCurrency: typeof import('./composables/useCurrency').useCurrency
  const useDark: typeof import('@vueuse/core').useDark
  const useExport: typeof import('./composables/useExport').useExport
  const useGoals: typeof import('./composables/useGoals').useGoals
  const useHead: typeof import('@unhead/vue').useHead
  const useI18n: typeof import('./composables/nuxt-compat').useI18n
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useLocalePath: typeof import('./composables/nuxt-compat').useLocalePath
  const useModel: typeof import('vue').useModel
  const useNetWorth: typeof import('./composables/useNetWorth').useNetWorth
  const useOnline: typeof import('@vueuse/core').useOnline
  const usePartner: typeof import('./composables/usePartner').usePartner
  const useReceipts: typeof import('./composables/useReceipts').useReceipts
  const useRecurring: typeof import('./composables/useRecurring').useRecurring
  const useReminders: typeof import('./composables/useReminders').useReminders
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSeoMeta: typeof import('@unhead/vue').useSeoMeta
  const useSlots: typeof import('vue').useSlots
  const useStorage: typeof import('@vueuse/core').useStorage
  const useSubscriptions: typeof import('./composables/useSubscriptions').useSubscriptions
  const useSupabase: typeof import('./lib/supabase').useSupabase
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useToast: typeof import('./composables/useToast').useToast
  const useToggle: typeof import('@vueuse/core').useToggle
  const useTransactionSummary: typeof import('./composables/useTransactions').useTransactionSummary
  const useTransactions: typeof import('./composables/useTransactions').useTransactions
  const useWindowScroll: typeof import('@vueuse/core').useWindowScroll
  const user: typeof import('./composables/useAuth').user
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { CameraPermissionState, UseCameraReturn } from './composables/useCamera'
  import('./composables/useCamera')
  // @ts-ignore
  export type { NetWorthData } from './composables/useNetWorth'
  import('./composables/useNetWorth')
  // @ts-ignore
  export type { UseReceiptsReturn } from './composables/useReceipts'
  import('./composables/useReceipts')
  // @ts-ignore
  export type { RecurringTransaction } from './composables/useRecurring'
  import('./composables/useRecurring')
  // @ts-ignore
  export type { Reminder } from './composables/useReminders'
  import('./composables/useReminders')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly cn: UnwrapRef<typeof import('./lib/utils')['cn']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly formatDateSafe: UnwrapRef<typeof import('./lib/utils')['formatDateSafe']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getOgImageUrl: UnwrapRef<typeof import('./lib/utils')['getOgImageUrl']>
    readonly getPageTitleKey: UnwrapRef<typeof import('./lib/utils')['getPageTitleKey']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly loadCurrency: UnwrapRef<typeof import('./composables/useCurrency')['loadCurrency']>
    readonly loading: UnwrapRef<typeof import('./composables/useAuth')['loading']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAccounts: UnwrapRef<typeof import('./composables/useAccounts')['useAccounts']>
    readonly useActivityLog: UnwrapRef<typeof import('./composables/useActivityLog')['useActivityLog']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAuth: UnwrapRef<typeof import('./composables/useAuth')['useAuth']>
    readonly useBills: UnwrapRef<typeof import('./composables/useBills')['useBills']>
    readonly useBudgets: UnwrapRef<typeof import('./composables/useBudgets')['useBudgets']>
    readonly useCamera: UnwrapRef<typeof import('./composables/useCamera')['useCamera']>
    readonly useCategories: UnwrapRef<typeof import('./composables/useCategories')['useCategories']>
    readonly useCategoryStats: UnwrapRef<typeof import('./composables/useTransactions')['useCategoryStats']>
    readonly useColorMode: UnwrapRef<typeof import('./composables/nuxt-compat')['useColorMode']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useCurrency: UnwrapRef<typeof import('./composables/useCurrency')['useCurrency']>
    readonly useDark: UnwrapRef<typeof import('@vueuse/core')['useDark']>
    readonly useExport: UnwrapRef<typeof import('./composables/useExport')['useExport']>
    readonly useGoals: UnwrapRef<typeof import('./composables/useGoals')['useGoals']>
    readonly useHead: UnwrapRef<typeof import('@unhead/vue')['useHead']>
    readonly useI18n: UnwrapRef<typeof import('./composables/nuxt-compat')['useI18n']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useLocalePath: UnwrapRef<typeof import('./composables/nuxt-compat')['useLocalePath']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNetWorth: UnwrapRef<typeof import('./composables/useNetWorth')['useNetWorth']>
    readonly useOnline: UnwrapRef<typeof import('@vueuse/core')['useOnline']>
    readonly usePartner: UnwrapRef<typeof import('./composables/usePartner')['usePartner']>
    readonly useReceipts: UnwrapRef<typeof import('./composables/useReceipts')['useReceipts']>
    readonly useRecurring: UnwrapRef<typeof import('./composables/useRecurring')['useRecurring']>
    readonly useReminders: UnwrapRef<typeof import('./composables/useReminders')['useReminders']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSeoMeta: UnwrapRef<typeof import('@unhead/vue')['useSeoMeta']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useStorage: UnwrapRef<typeof import('@vueuse/core')['useStorage']>
    readonly useSubscriptions: UnwrapRef<typeof import('./composables/useSubscriptions')['useSubscriptions']>
    readonly useSupabase: UnwrapRef<typeof import('./lib/supabase')['useSupabase']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useToast: UnwrapRef<typeof import('./composables/useToast')['useToast']>
    readonly useToggle: UnwrapRef<typeof import('@vueuse/core')['useToggle']>
    readonly useTransactionSummary: UnwrapRef<typeof import('./composables/useTransactions')['useTransactionSummary']>
    readonly useTransactions: UnwrapRef<typeof import('./composables/useTransactions')['useTransactions']>
    readonly useWindowScroll: UnwrapRef<typeof import('@vueuse/core')['useWindowScroll']>
    readonly user: UnwrapRef<typeof import('./composables/useAuth')['user']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}